from revenue_swarm.config import getenv


PUBLISH_ENABLED = getenv("PUBLISH_ENABLED", "0") == "1"
PUBLISH_TARGET_BLOG = getenv("PUBLISH_TARGET_BLOG", "dryrun")
PUBLISH_TARGET_SOCIAL = getenv("PUBLISH_TARGET_SOCIAL", "dryrun")
PUBLISH_MAX_PER_RUN = int(getenv("PUBLISH_MAX_PER_RUN", "3"))
PUBLISH_MIN_INTERVAL_SECONDS = int(
    getenv("PUBLISH_MIN_INTERVAL_SECONDS", "60")
)
PUBLISH_MAX_ATTEMPTS = int(getenv("PUBLISH_MAX_ATTEMPTS", "3"))
PUBLISH_WINDOW_HOURS = getenv("PUBLISH_WINDOW_HOURS", "8-20")

WORDPRESS_BASE_URL = getenv("WORDPRESS_BASE_URL", "").rstrip("/")
WORDPRESS_USER = getenv("WORDPRESS_USER", "")
WORDPRESS_APP_PASSWORD = getenv("WORDPRESS_APP_PASSWORD", "")
WORDPRESS_POST_STATUS = getenv("WORDPRESS_POST_STATUS", "draft")

MASTODON_BASE_URL = getenv("MASTODON_BASE_URL", "").rstrip("/")
MASTODON_TOKEN = getenv("MASTODON_TOKEN", "")
X_BEARER_TOKEN = getenv("X_BEARER_TOKEN", "")
