"""create publications

Revision ID: 0786e80df98e
Revises: 0d0347e931ad
Create Date: 2026-10-08 03:43:27.221712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0786e80df98e'
down_revision: Union[str, Sequence[str], None] = '0d0347e931ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_item_id', sa.UUID(), nullable=False),
    sa.Column('target', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('external_url', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_item_id', 'target', name='uq_publication')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publications')
    # ### end Alembic commands ###
