"""fix_source_task_id_typo

Revision ID: 1a752ac46670
Revises: 695308f38902
Create Date: 2026-09-01 23:35:09.607991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a752ac46670'
down_revision: Union[str, Sequence[str], None] = '695308f38902'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('affiliate_programs', sa.Column('source_task_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('affiliate_programs_source_taask_id_fkey'), 'affiliate_programs', type_='foreignkey')
    op.create_foreign_key(None, 'affiliate_programs', 'agent_tasks', ['source_task_id'], ['id'])
    op.drop_column('affiliate_programs', 'source_taask_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('affiliate_programs', sa.Column('source_taask_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'affiliate_programs', type_='foreignkey')
    op.create_foreign_key(op.f('affiliate_programs_source_taask_id_fkey'), 'affiliate_programs', 'agent_tasks', ['source_taask_id'], ['id'])
    op.drop_column('affiliate_programs', 'source_task_id')
    # ### end Alembic commands ###
