"""content agent fields

Revision ID: 93e9e70c8056
Revises: b004413411e4
Create Date: 2026-09-21 23:44:20.733887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93e9e70c8056'
down_revision: Union[str, Sequence[str], None] = 'b004413411e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('affiliate_programs', sa.Column('affiliate_link', sa.Text(), nullable=True))
    op.add_column('content_items', sa.Column('source_task_id', sa.UUID(), nullable=True))
    op.add_column('content_items', sa.Column('extras', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('content_items', sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True))
    op.add_column('content_items', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('content_items', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_foreign_key(None, 'content_items', 'agent_tasks', ['source_task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'content_items', type_='foreignkey')
    op.drop_column('content_items', 'updated_at')
    op.drop_column('content_items', 'published_at')
    op.drop_column('content_items', 'scheduled_for')
    op.drop_column('content_items', 'extras')
    op.drop_column('content_items', 'source_task_id')
    op.drop_column('affiliate_programs', 'affiliate_link')
    # ### end Alembic commands ###
