"""program score

Revision ID: b5a054a7c1fb
Revises: 93e9e70c8056
Create Date: 2026-09-28 02:02:42.088787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5a054a7c1fb'
down_revision: Union[str, Sequence[str], None] = '93e9e70c8056'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('affiliate_programs', sa.Column('score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('affiliate_programs', 'score')
    # ### end Alembic commands ###
